document.getElementById("quote-btn").onclick = function randomQuote() {
    let quotes = [
        "Whether you think you can or you think you can't, you're right. -Henry Ford",
        "You miss 100% of the shots you don't take. -Wayne Gretzky",
        "The best way to cheer yourself is to try to cheer someone else up. -Mark Twain",
        "It's hard to beat a person who never gives up. -Babe Ruth",
        "Problems are not stop signs; they are guidelines. -Robert Schuller",
        "Problems are not stop signs; they are guidelines. -Robert Schuller",
        "When you come to the edge of all that you know, you must believe one of two things: There will be ground to stand. Or you will grow wings to fly. -O.R. Melling",
        "It's better to be in the arena, getting stomped by a bull, than to be up in the stands or out in the parking lot. -Steven Pressfield",
        "Success isn't permanent and failure isn't fatal; it's the courage to continue that counts. -Mike Ditka",
        "Courage doesn't always roar. Sometimes courage is the little voice at the end of the day that says I'll try again tomorrow. -Mary Anne Radmacher",
        "You shouldn't focus on why you can't do something, which is what most people do. You should focus on why perhaps you can, and be one of the exceptions. -Steve Case",
        "Watch the sunrise at least once a year, put a lot of marshmallows in your hot chocolate, lie on your back and look at the stars, never buy a coffee table you can't put your feet on, never pass up a chance to jump on a trampoline, don't overlook life's small joys while searching for the big ones. -H. Jackson Brown Jr.",
        "When you get into a tight place and everything goes against you, till it seems as though you could not hold on a minute longer, never give up then, for that is just the place and time that the tide will turn. -Harriet Beecher Stowe",
        "There's nothing wrong or evil about having a bad day. There's everything wrong with making others have to have it with you. -Neil Cavuto",
        "Someday everything will make perfect sense. So, for now, laugh at the confusion, smile through the tears, and keep reminding yourself that everything happens for a reason. -Unknown",
        "Some days you tame the tiger. And some days the tiger has you for lunch. -Tug McGraw",
        "The one law that does not change is that everything changes, and the hardship I was bearing today was only a breath away from the pleasures I would have tomorrow, and those pleasures would be all the richer because of the memories of this I was enduring. -Louis L'Amour",
        "You make mistakes. Mistakes don't make you. -Maxwell Maltz",
        "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all. -Dale Carnegie",
        "There is neither happiness nor unhappiness in this world; there is merely the comparison of one state to the other. Only a man who has felt ultimate despair is capable of feeling ultimate bliss. -Alexandre Dumas",
        "Many of life's failures are people who did not realize how close they were to success when they gave up. -Thomas Edison",
        "It's just a bad day. Not a bad life. -Unknown",
        "You may encounter many defeats, but you must not be defeated. In fact, it may be necessary to encounter the defeats, so you can know who you are, what you can rise from, how you can still come out of it. -Maya Angelou",
        "Life is short. Smile while you still have teeth. -Unknown",
        "Don't be discouraged. It's often the last key in the bunch that opens the lock. -Unknown",
        "No one is going to hand me success. I must go out and get it myself. That's why I'm here. To dominate. To conquer. Both the world and myself. -Unknown",
        "Things don't go wrong and break your heart so you can become bitter and give up. They happen to break you down and build you up so you can be all that you were intended to be. -Samuel Johnson",
        "Every strike brings me closer to the next home run. -Babe Ruth",
        "The happiest people don't necessarily have the best of everything, they just make the best out of everything that comes their way. -Unknown",
        "When things are bad, we take comfort in the thought that they could always get worse. And when they are, we find hope in the thought that things are so bad they have to get better. -Malcolm S. Forbes",
        "What lies behind you and what lies in front of you pales in comparison to what lies inside of you. -Ralph Waldo Emerson",
        "Pain is temporary. Quitting lasts forever. -Lance Armstrong",
        "You yourself, as much as anybody in the entire universe, deserve your love and affection. -Gautama Buddha",
        "The only time you fail is when you fall down and stay down. -Stephen Richards",
        "Count your age by friends, not years. Count your life by smiles, not tears. -John Lennon",
        "Tough times never last, but tough people do. -Robert H. Schuller",
        "If you're reading this ... Congratulations, you're alive. If that's not something to smile about, then I don't know what is. -Chad Sugg",
        "Every single day is a good day no matter how bright or dark it is, because it always brings an opportunity to start a positive beginning in your life. -Edmond Mbiaka",
        "For every minute you are angry you lose 60 seconds of happiness. -Ralph Waldo Emerson",
        "Being happy doesn't mean you're perfect. It just means you've decided to look beyond the imperfections. -K.B. Indiana",
        "Every day may not be good, but there's something good in every day. -Unknown",
        "You don't develop courage by being happy in your relationships every day. You develop it by surviving difficult times and challenging adversity. -Epicurus",
        "If you are feeling low or trampled, unappreciated or forgotten and you are reading this, realize it is an illusion. The hope is real, you are valued, and what lies ahead is brilliance. -Tom Althouse",
        "Pressure is nothing more than the shadow of great opportunity. — Michael Johnson",
        "Effective people are not problem-minded; they're opportunity-minded. They feed opportunities and starve problems. — Stephen Covey",
        "Turbulence is life force. It is opportunity. Let's love turbulence and use it for change. — Ramsey Clark",
        "There is no security on this earth; there is only opportunity. — Douglas MacArthur",
        "Whenever you see darkness, there is extraordinary opportunity for the light to burn brighter. — Bono",
        "Problems can become opportunities when the right people come together. — Robert Redford",
        "New beginnings are often disguised as painful endings. — Lao Tzu",
        "The true measure of success is how many times you can bounce back from failure. — Stephen Richards",
        "Opportunities do not come with their values stamped upon them. Everyone must be challenged. A day dawns, quite like other days; in it, a single hour comes, quite like other hours; but in that day and in that hour the chance of a lifetime faces us. — Maltbie Davenport Babcock",
        "Every wall is a door. — Ralph Waldo Emerson",
        "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty. — Winston S. Churchill",
        "Entrepreneurs are simply those who understand that there is little difference between obstacle and opportunity and are able to turn both to their advantage. — Victor Kiam",
        "When written in Chinese, the word 'crisis' is composed of two characters. One represents danger and the other represents opportunity. — John F. Kennedy",
        "I always tried to turn every disaster into an opportunity. — John D. Rockefeller",
        "Every twist and turn in life is an opportunity to learn something new about yourself, your interests, your talents, and how to set and then achieve goals. — Jameela Jamil",
        "Victory comes from finding opportunities in problems. — Sun Tzu",
        "Innovation is the ability to see change as an opportunity, not a threat. — Steve Jobs",
        "Turn your obstacles into opportunities and your problems into possibilities. — Roy T. Bennett",
        "What is the difference between an obstacle and an opportunity? Our attitude toward it. Every opportunity has a difficulty, and every difficulty has an opportunity. — J. Sidlow Baxter",
        "Opportunities are like sunrises. If you wait too long, you miss them. — William Arthur Ward",
        "Too many people are thinking of security instead of opportunity. They seem more afraid of life than death. — James F. Byrnes",
        "Circumstances may cause interruptions and delays, but never lose sight of your goal. Prepare yourself in every way you can by increasing your knowledge and adding to your experience, so that you can make the most of opportunity when it occurs. — Mario Andretti",
        "One secret of success in life is for a man to be ready for his opportunity when it comes. — Benjamin Disraeli",
        "At various points in your careers, you will be called to take a risk. And I think you will find, as I have found, those will be the times of your greatest opportunities. — Raymond V. Gilmartin",
        "Opportunities multiply as they are seized. — Sun Tzu",
        "If a window of opportunity appears, don't pull down the shade. — Tom Peters",
        "Our lives are defined by opportunities. Even the ones we miss. — F. Scott Fitzgerald",
        "Life opens up opportunities to you, and you either take them or you stay afraid of taking them. — Jim Carrey",
        "Nothing is more expensive than a missed opportunity. — H. Jackson Brown Jr.",
        "Jump at opportunities to take on responsibilities. People should try new things, that's how to grow. — Kevin Murray",
        "When a great moment knocks on the door of your life, it is often no louder than the beating of your heart, and it is very easy to miss it. — Boris Pasternak",
        "If you have the opportunity to play this game of life, you need to appreciate every moment. A lot of people don't appreciate the moment until it's passed. — Kanye West",
        "Everyone has something to contribute to this world. It's just a matter of being given that opportunity to do so. — Grace Hightower",
        "Not knowing when the dawn will come, I open every door. — Emily Dickinson",
        "When opportunity presents itself, don't be afraid to go after it. — Eddie Kennison",
        "The sad truth is that opportunity doesn't knock twice. — Gloria Estefan",
        "Most successful men have not achieved their distinction by having some new talent or opportunity presented to them. They have developed the opportunity that was at hand. — Bruce Barton",
        "When one door closes, another door opens; but we so often look so long and so regretfully upon the closed door, that we do not see the ones which open for us. — Alexander Graham Bell",
        "In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks. — Mark Zuckerberg",
        "Business opportunities are like buses, there's always another one coming. — Richard Branson",
        "Enjoying success requires the ability to adapt. Only by being open to change will you have a true opportunity to get the most from your talent. — Nolan Ryan",
        "He who refuses to embrace a unique opportunity loses the prize as surely as if he had tried and failed. — William James",
        "Most people miss great opportunities because of their misperception of time. Don't wait! The time will never be just right. — Stephen C. Hogan",
        "Every moment wasted looking back, keeps us from moving forward. — Hillary Clinton",
        "How much I missed, simply because I was afraid of missing it. — Paulo Coelho",
        "Most do not understand the wonderful opportunities life gives until they look back at their life. — Eric Handler",
        "Opportunities? They are all around us... There is power lying latent everywhere waiting for the observant eye to discover it. — Orison Swett Marden",
        "Your regrets aren't what you did, but what you didn't do. So I take every opportunity. — Cameron Diaz",
        "I will prepare and someday my chance will come. — Abraham Lincoln",
        "To stay ahead, you must have your next idea waiting in the wings. — Rosabeth Moss Kanter",
        "Be a magnet that draws opportunity. Paint brilliant thoughts and actions. Mirror success. — Shawn L. Anderson",
        "Aging is not lost youth but a new stage of opportunity and strength. — Betty Friedan",
        "Don't wait for the right opportunity: create it. — George Bernard Shaw",
        "Expect change. Analyze the landscape. Take the opportunities. Stop being the chess piece; become the player. It's your move. — Tony Robbins",
        "Opportunities and success are not something you go after necessarily but something you attract by becoming an attractive person. — Jim Rohn",
        "As we enjoy great adventures from the inventions of others, we should be glad of an opportunity to serve others by an invention of ours, and this we should do freely and generously. — Benjamin Franklin",
        "Let your hook be always cast; in the pool where you least expect it, there will be a fish. — Ovid",
        "We will open the book. Its pages are blank. We are going to put words on them ourselves. The book is called Opportunity and its first chapter is New Year's Day. — Edith Lovejoy Pierce",
        "A wise man will make more opportunities than he finds. — Francis Bacon",
        "It's through curiosity and looking at opportunities in new ways that we've always mapped our path. — Michael Dell",
        "To hell with circumstances; I create opportunities. — Bruce Lee",
        "We are all inventors, each sailing out on a voyage of discovery, guided each by a private chart, of which there is no duplicate. The world is all gates, all opportunities. — Ralph Waldo Emerson",
        "Today knowledge has power. It controls access to opportunity and advancement. — Peter Drucker",
        "Opportunities, many times, are so small that we glimpse them not and yet they are often the seeds of great enterprises. Opportunities are also everywhere and so you must always let your hook be hanging. When you least expect it, a great fish will swim by. — Og Mandino",
        "Decide what you want, and then act as if it were impossible to fail. — Brian Tracy",
        "The golden opportunity you are seeking is in yourself. It is not in your environment; it is not in luck or chance or the help of others; it is in yourself alone. — Orison Swett Marden",
        "Your big opportunity may be right where you are now. — Napoleon Hill",
        "As long as you are going to be thinking anyway, think big. — Donald Trump",
        "Small opportunities are often the beginning of great enterprises. — Demosthenes",
        "Ability is of little account without opportunity. — Lucille Ball",
        "It is possible to become discouraged about the injustice we see everywhere. But God did not promise us that the world would be humane and just. He gives us the gift of life and allows us to choose the way we will use our limited time on earth. It is an awesome opportunity. — Cesar Chavez",
        "The entrepreneur always searches for change, responds to it, and exploits it as an opportunity. — Peter Drucker",
        "Teachers open the doors, but you must enter by yourself. — Chinese proverb",
        "Success is where preparation and opportunity meet. — Bobby Unser",
        "I believe success is preparation because opportunity is going to knock on your door sooner or later, but are you prepared to answer that? — Omar Epps",
        "I believe that every right implies a responsibility; every opportunity, an obligation; every possession, a duty. — John D. Rockefeller",
        "The future depends on what you do today. — Mahatma Gandhi"

    ];

    let randomIndex = Math.floor(Math.random() * quotes.length);
    let randomQuote = quotes[randomIndex];

    document.getElementById("quote").innerText = randomQuote;
}